### ISSUE TITLE
World Log Could not be created on dedicated server

### ISSUE THREAD

**Issue by Alaberti** [PC-Logix/LanteaCraft#315]
I get the following on a dedicated server; I can fix it easily enough by adding the save folder, however I believe there should be a check against a dedicated server, vs the internal one, for save location - or it could create the directory if it can't find it. Good news, it doesn't crash anything. Using build 70 on Forge 1307.

[12:01:00] [Server thread/INFO] [LanteaCraft]: WorldLog starting: /home/gp/3233/userdata/grimoire_magus/saves/transistor/data/LanteaCraft.log
[12:01:00] [Server thread/WARN] [LanteaCraft]: Could not create WorldLog, an error occured.
java.io.FileNotFoundException: /home/gp/3233/userdata/grimoire_magus/saves/transistor/data/LanteaCraft.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method) ~[?:1.7.0_75]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[?:1.7.0_75]
	at pcl.lc.core.WorldLog.open(WorldLog.java:32) [WorldLog.class:?]
	at pcl.lc.LanteaCraftCommonProxy.onServerStarting(LanteaCraftCommonProxy.java:204) [LanteaCraftCommonProxy.class:?]
	at pcl.lc.LanteaCraft.onServerStarting(LanteaCraft.java:133) [LanteaCraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by AfterLifeLochie** [comment]
This is a known issue. You can chose to either create the directory required, or just ignore the message - it won't stop the server from starting.

This won't be fixed because WorldLog is no longer a thing in the rewrite.

**Comment by Alaberti** [comment]
Thought so, alright, thanks for the feedback!
