### ISSUE TITLE
Unhandled exception in ITickAgent

### ISSUE THREAD

**Issue by hehe3301** [PC-Logix/LanteaCraft#321]
Error message coming in on server log every tick and gates are not dialable.

[10:14:23] [Server thread/WARN] [LanteaCraft]: Unhandled exception in ITickAgent.
java.lang.NullPointerException

**Comment by AfterLifeLochie** [comment]
That's not a helpful issue report. We need more than just "NullPointerException", give us the full trace instead.

**Comment by AfterLifeLochie** [comment]
@hehe3301 Unless you give me more info so I can fix this, I will have to close it.

**Comment by CaitlynMainer** [comment]
I just had this on my private server, trying to dial from Nether to Overworld, the overworld gate was loaded as another player was looking at it as I was dialing, https://pc-logix.com/fml-server-latest.log

**Comment by AfterLifeLochie** [comment]
What effect does this issue have on the server?

**Comment by CaitlynMainer** [comment]
The gate stopped dialing about 3 chevrons in, and randomly connected a few minutes later.  Both gates had stopped showing any activity until the random connection.

**Comment by joshthegrate** [comment]
experiencing the same issue getting this spammed while the gate is dialing

[15:35:23] [Server thread/WARN] [LanteaCraft/]: Unhandled exception in ITickAgent.
java.lang.NullPointerException
	at pcl.lc.module.stargate.StargateConnectionManager$ConnectionRequest.advance(StargateConnectionManager.java:229) ~[StargateConnectionManager$ConnectionRequest.class:?]
	at pcl.lc.module.stargate.StargateConnectionManager.advance(StargateConnectionManager.java:309) ~[StargateConnectionManager.class:?]
	at pcl.lc.base.TickHandler.tickChildren(TickHandler.java:51) [TickHandler.class:?]
	at pcl.lc.core.ServerTickHandler.onWorldTick(ServerTickHandler.java:25) [ServerTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_431_ServerTickHandler_onWorldTick_ServerTickEvent.invoke(.dynamic) [?:KCauldron-1.7.10-5.1403.71]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:KCauldron-1.7.10-5.1403.71]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:KCauldron-1.7.10-5.1403.71]
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:KCauldron-1.7.10-5.1403.71]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by AfterLifeLochie** [comment]
This appears to only occur in instances where the Stargate block is found but is then unloaded by the game. It is likely indicative of either a chunk-loading issue or a wider problem with Stargate caching.

I will attempt to patch this, though the underlying issue has been resolved in LC 2.0 retroactively.

**Comment by AfterLifeLochie** [comment]
There won't be any fix for this issue in the legacy tree. You should upgrade to a newer version  if you haven't already.
