### ISSUE TITLE
LC2-15 | Placing a brazier will crash the server.

### ISSUE THREAD

**Issue by FNCxPro** [PC-Logix/LanteaCraft#394]
I experienced this bug while placing a brazier. The server crashed, but not the client.

Crash Report: http://pastebin.com/dqTdiUdm
Mod List: http://technicpack.net/modpack/flyte-modpack.767630/mods

Server is running KCauldron.
Server Forge: 1566

**Comment by FNCxPro** [comment]
Also, if I may add: the server does not crash after starting it up again. However, it makes reading logs atrocious because the next two errors are spammed.
````
[16:56:35] [Server thread/FATAL]: Couldn't create new instance of tile type.
java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66-internal]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_66-internal]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_66-internal]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_66-internal]
	at lc.common.base.LCBlock.func_149915_a(LCBlock.java:206) [LCBlock.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1464) [aji.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:925) [apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:3126) [ahb.class:?]
	at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:37) [LCTargetPacket.class:?]
	at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
	at lc.common.network.LCNetworkController.think(LCNetworkController.java:74) [LCNetworkController.class:?]
	at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
	at lc.common.util.game.LCTickConnector.onWorldTick(LCTickConnector.java:67) [LCTickConnector.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_3_LCTickConnector_onWorldTick_ServerTickEvent.invoke(.dynamic) [?:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:1.7.10-1566.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66-internal]
	... 20 more
[16:56:35] [Server thread/WARN]: Unhandled exception in ITickEventHandler.
java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_66-internal]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_66-internal]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_66-internal]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_66-internal]
	at lc.common.base.LCBlock.func_149915_a(LCBlock.java:206) ~[LCBlock.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1464) ~[aji.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:925) ~[apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:3126) ~[ahb.class:?]
	at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:37) ~[LCTargetPacket.class:?]
	at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) ~[LCNetworkQueue.class:?]
	at lc.common.network.LCNetworkController.think(LCNetworkController.java:74) ~[LCNetworkController.class:?]
	at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
	at lc.common.util.game.LCTickConnector.onWorldTick(LCTickConnector.java:67) [LCTickConnector.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_3_LCTickConnector_onWorldTick_ServerTickEvent.invoke(.dynamic) [?:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1566.UNOFFICIAL]
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:1.7.10-1566.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66-internal]
	... 20 more
````

**Comment by AfterLifeLochie** [comment]
Apparently `IParticleMachine` references `EntityFX` directly, and not an LC-ified version. My bad.
