### ISSUE TITLE
Gate causing crash server and client

### ISSUE THREAD

**Issue by ver1tatem** [PC-Logix/LanteaCraft#405]
I'm having an issue between Lanteacraft and Galacticraft. Any stargates on a space station randomly become individual blocks again despite being a complete formation. Placing a block in the middle and destroying it will fix this but it has caused more issues now. Gates that have this glitch cannot be dialed. If the gate is dialed nothing will happen to the gate, the client will get DC'd and the server will crash claiming there's still one player inside. Any help would be greatly appreciated

**Comment by CaitlynMainer** [comment]
A crash log would be helpful.

**Comment by AfterLifeLochie** [comment]
Unless you provide more info, I will have to close this. "It doesn't work" definitely isn't sufficient.

**Comment by ver1tatem** [comment]
Sorry for not including more info on the original post. I just started a new job yesterday and I wasn't sure if it was even recording this issue in the logs. 
Video of error occurring: https://www.dropbox.com/s/qo45zxdwumxtu37/Game%20crash%20example.mov?dl=0

Image of Successful Login (everything else works ok)
https://www.dropbox.com/s/65scghn1t2il914/Succesful%20Login.png?dl=0

Errors After Dialing:
https://www.dropbox.com/s/3pk3isjs7mfvee8/Errors%20After%20Dialing.png?dl=0

Log File:
https://www.dropbox.com/s/93i7q717j9x18gw/latest.log?dl=0

I'll try to include images of the gate disassembling when I can hopefully this is enough for now? Again apologies for not including it initially

**Comment by ver1tatem** [comment]
And here's the photo of it becoming individual blocks. I believe it may have to do with the fact the area is sealed by Galacticraft? If I recall Galacticraft sealers search the entire area for openings before sealing and do so continuously, maybe something to do with that?  https://www.dropbox.com/s/ugkl2sz81m6c3xm/Screen%20Shot%202016-01-12%20at%206.37.13%20PM.png?dl=0
Sometimes the gate is appearing as (1/3 the finalized gate image)+(2/3 just the blocks) and when this happens the gate is somewhat useable meaning I can make outgoing wormholes but can't receive them. Once it's deteriorated into individual blocks again (like in the picture) it stops working completely until you place a block into the middle and break it. I didn't believe it was recording the issues in the log since nothing appears after I dial the gate in the video shown. 
Specific errors that pop up anytime I try to access that area anymore
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.Exception: Stack trace
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.dumpStack(Thread.java:1329)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:470)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[19:33:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I now have to delete the spacestation dimension to use the server on said account anymore since it will lock up like this anytime I log in. I don't have enough time to TP myself to a different location at this point. (It's a good thing I backup every day)

**Comment by ver1tatem** [comment]
Also unsure if mentioned but this is the public release of LanteaCraft 1.7.10-70. Would love any help because I've made a new server same issue occurs from scratch just takes time and a space station like I mentioned.

**Comment by LemADEC** [comment]
Looks like your gates are built over chunkborders, try to fit them in same chunk, see it shows same issue.

**Comment by ver1tatem** [comment]
Do you say that because I took the screenshot when I loaded in and a chunk was still loading? Just curious how to know this and try your steps. (Video shows how the gate still functions in state)

**Comment by AfterLifeLochie** [comment]
You should try upgrading to the newer unstable sources.

If this is a bug in the older build set, it probably won't be fixed.

**Comment by ver1tatem** [comment]
Thank you AfterLifeLochie I'll give it a shot and report back

**Comment by LemADEC** [comment]
We had the same issue back in 1.6.4 using LanteaCraft and the original SGCraft. When the gate is accross chunk, it was not forming properly when loading the world.
From your screenshot, you have a whole side corrupted, which goes with the same hypothesis.

**Comment by AfterLifeLochie** [comment]
This bug will not be fixed as LC2 builds are now promoted to release in order to replace these buggy ones.
