### ISSUE TITLE
Failed to generate scattered structures.

### ISSUE THREAD

**Issue by LemADEC** [PC-Logix/LanteaCraft#414]
When exploring the world, console is spammed with errors from the mod:
```
[06:00:03 WARN]: Failed to generate scattered structures.
java.lang.NullPointerException
>       at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:91) ~[ave.class:?]
>       at lc.common.base.generation.LCMasterWorldGen.generate(LCMasterWorldGen.java:57) [LCMasterWorldGen.class:?]
>       at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137) [GameRegistry.class:1.7.10-R0.1-SNAPSHOT]
>       at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:441) [ms.class:?]
>       at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1187) [apx.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:296) [ms.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:202) [ms.class:?]
>       at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) [mr.class:?]
>       at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) [mq.class:?]
>       at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:212) [mq.class:?]
>       at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:305) [mq.class:?]
>       at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:413) [oi.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:583) [nh.class:?]
>       at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
>       at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

I've set B:GenerateStructures=false in the configuration, but it didn't help.
Issue with reproduced with both KCauldron-1.7.10-1614.200.jar and Thermos-1.7.10-1614-46-server.jar.
I'm using LanteaCraft-1.7.10-unstable16.jar

In a side note, your jenkins is down.

**Comment by LemADEC** [comment]
Issue is reproduced in single player with Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10

**Comment by AfterLifeLochie** [comment]
Jenkins is up at http://jenkins.pc-logix.com , but you cannot download files from there.

LanteaCraft does not use the original CFG configuration, so changing settings in `LanteaCraft.cfg` will not help. You must disable options in `LanteaCraft.xml` instead. 

Fixed in commit 6cec49729acb3a725c9c561803f9577ac7ad8f94.

**Comment by LemADEC** [comment]
Any chance we get a snapshot of this fix?

**Comment by ver1tatem** [comment]
Apologies did not see this thread I must be blind. Suffering the same issue =/

**Comment by AfterLifeLochie** [comment]
Build 19 has the fix.
