### ISSUE TITLE
Error when processing callback lcpd_handleEvent! java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by UnixRonin** [PC-Logix/LanteaCraft#423]
FYI, with LanteaCraft2 build 21 on Forge, I'm seeing many occurrences of the following warning logged.  I don't know how important it actually is, but it doesn't look good to me.  Seems to be some kind of array underflow.

[11:42:11 WARN]: Error when processing callback lcpd_handleEvent!
java.lang.NegativeArraySizeException
        at lc.common.util.ReflectionHelper.invokeWithExpansions(ReflectionHelper.java:56) ~[ReflectionHelper.class:?]
        at lc.common.base.LCTile.doCallbacks(LCTile.java:157) [LCTile.class:?]
        at lc.common.base.LCTile.doCallbacksNow(LCTile.java:113) [LCTile.class:?]
        at lc.tiles.TileStargateBase.notifyConnectionState(TileStargateBase.java:849) [TileStargateBase.class:?]
        at lc.server.StargateConnection.sendUpdates(StargateConnection.java:192) [StargateConnection.class:?]
        at lc.server.StargateConnection.changeState(StargateConnection.java:184) [StargateConnection.class:?]
        at lc.server.StargateConnection.thinkSpinDown(StargateConnection.java:155) [StargateConnection.class:?]
        at lc.server.StargateConnection.think(StargateConnection.java:92) [StargateConnection.class:?]
        at lc.server.StargateManager.think(StargateManager.java:133) [StargateManager.class:?]
        at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
        at lc.common.util.game.LCTickConnector.onWorldTick(LCTickConnector.java:67) [LCTickConnector.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_LCTickConnector_onWorldTick_ServerTickEvent.invoke(.dynamic) [?:1.7.10-1614.175]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.175]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.175]
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264) [FMLCommonHandler.class:1.7.10-1614.175]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by AfterLifeLochie** [comment]
It looks like this is a pretty serious bug, but fortunately it doesn't so much matter if `lcpd_handleEvent` is invoked or not. Thanks for the catch.

In future, if you could follow the issue template (even if it doesn't seem appropriate), that'd be appreciated; I automatically parse the issue texts.

**Comment by AfterLifeLochie** [comment]
Fixed in commit 2ca1d1dddb26113291d88716f3106fec4a81be23.
