### ISSUE TITLE
error + freeze

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#440]
Sometimes this error spams in my log and game for short time freeze.

<code>[20:50:36] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]</code>

**Comment by AfterLifeLochie** [comment]
I'm not sure why the game would be freezing, but this is an indication that LC is getting packets from the server for TileEntities in chunks which aren't loaded on the client. You'd only get this message as a side-effect of a bigger client problem (ie, game freezing, network latency problem, chunks not available).

**Comment by Cronosus** [comment]
may be cause by different chunkloading radius between client and server?
but this log is from SP, and i have very fast pc...

**Comment by AfterLifeLochie** [comment]
You would need to attach a debugger to see why the game is freezing -- that'll probably be what's causing the issue, since if you're in SSP you shouldn't see these kinds of messages.

**Comment by AfterLifeLochie** [comment]
fwiw, if you think this is LanteaCraft causing the freeze, please send me a copy of your `logs/lanteacraft/performance.log` so that I can take a look at the internal profiling data. The other files there (`core.log` and `game.log`) wouldn't hurt either if you've got them.

**Comment by Cronosus** [comment]
here..
http://cronos.wz.cz/mc/lc/core.log
http://cronos.wz.cz/mc/lc/game.log

**Comment by lyqyd** [comment]
You've omitted the `performance.log`, was it not present?

**Comment by Cronosus** [comment]
sry
http://cronos.wz.cz/mc/lc/performance.log

**Comment by AfterLifeLochie** [comment]
You're running an unofficial build since you don't have a version tag.

**Comment by Cronosus** [comment]
files updated from last build22
not same as before, but something still there..

**Comment by AfterLifeLochie** [comment]
![](http://puu.sh/sv0Hc/f82dbbc3f7.png)

From the profiling data it looks like there isn't anything causing serious hangups, not directly. Most of the average times are well within fractions of a milisecond, though you're getting some strange Worst Time hits on the tile entity `func_145845_h` method. I need more detail about your environment to be able to fix this problem.
