### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#443]
game sometimes randomly crashes (happened on SP, only LC-21, forge 10.13.4.1614)
<code>
[10:45:12] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[10:45:12] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[10:45:12] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[10:45:12] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[10:45:12] [Client thread/WARN] [LanteaCraft]: Problem handling packet in queue.
lc.common.network.LCNetworkException: Invalid target tile specified.
    at lc.common.network.packets.abs.LCTargetPacket.handlePacket(LCTargetPacket.java:42) ~[LCTargetPacket.class:?]
    at lc.common.network.LCNetworkQueue.think(LCNetworkQueue.java:68) [LCNetworkQueue.class:?]
    at lc.common.network.LCNetworkController.think(LCNetworkController.java:81) [LCNetworkController.class:?]
    at lc.common.util.game.LCTickConnector.doTick(LCTickConnector.java:104) [LCTickConnector.class:?]
    at lc.common.util.game.LCTickConnector.onClientTick(LCTickConnector.java:81) [LCTickConnector.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_LCTickConnector_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
</code>

**Comment by AfterLifeLochie** [comment]
`LCNetworkException: Invalid target tile specified` is thrown if the client receives a LanteaCraft packet for a TileEntity which isn't valid on the client (not loaded yet, out of range, etc). Since buffering them would create artificial lag, these packets are just ignored. If you see this frequently, though, please let me know what you're doing specifically.
