### ISSUE TITLE
Server Console error FileNotFoundException: http://lanteacraft.com/api/beacon

### ISSUE THREAD

**Issue by ProsperCraft** [PC-Logix/LanteaCraft#451]
[19:39:17] [LanteaCraft beacon worker/WARN] [LanteaCraft]: Beacon task I/O error.
java.io.FileNotFoundException: http://lanteacraft.com/api/beacon
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464) ~[?:1.8.0_111]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463) ~[?:1.8.0_111]
        at lc.common.util.BeaconStreamThread.runTask(BeaconStreamThread.java:95) ~[BeaconStreamThread.class:?]
        at lc.common.util.BeaconStreamThread.run(BeaconStreamThread.java:71) [BeaconStreamThread.class:?]

- MinecraftForge version: forge-1.7.10-10.13.4.1614-1.7.10
- LanteaCraft version: LanteaCraft-1.7.10-22.jar

**Comment by CaitlynMainer** [comment]
This is a known issue. I moved the website to a new server and haven't got everything working yet.
